opt_out_usage
# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to AppCenter"
  lane :alpha do
    build_number = number_of_commits() 
    Dir.chdir "../.." do
      sh("flutter", "build", "apk", "--release", "--build-number=#{build_number}")
    end

    changelog_from_git_commits(
      pretty: "- %s",
      date_format: "short",
      match_lightweight_tag: false,
      commits_count: 5,
    )
    
    appcenter_upload(
      app_name: "Notes-App-Android",
      apk: "../build/app/outputs/apk/release/app-release.apk",
      destinations: "Alpha", 
      notify_testers: true,
      release_notes: lane_context[SharedValues::FL_CHANGELOG]
    )
    
    slack(
      message: "App successfully built!",
      payload: {
        "Download URL" => lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]
      }
    )
  end

  lane :beta do
    build_number = number_of_commits() 
    Dir.chdir "../.." do
      sh("flutter", "build", "apk", "--release", "--build-number=#{build_number}")
    end

    changelog_from_git_commits(
      pretty: "- %s",
      date_format: "short",
      match_lightweight_tag: false,
      commits_count: 5,
    )
    
    appcenter_upload(
      app_name: "Notes-App-Android",
      apk: "../build/app/outputs/apk/release/app-release.apk",
      destinations: "Beta", 
      notify_testers: true,
      release_notes: lane_context[SharedValues::FL_CHANGELOG]
    )
    
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      apk_path: "../build/app/outputs/apk/release/app-release.apk",
      groups: "BETA",
      release_notes: lane_context[SharedValues::FL_CHANGELOG],
      firebase_cli_path: "/Users/runner/firebase_tools"
    )

    slack(
      message: "App successfully built!",
      payload: {
        "Download URL" => lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]
      }
    )
  end


  lane :bundle do
    build_number = number_of_commits()  
    Dir.chdir "../.." do
      sh("flutter", "build", "appbundle", "--release", "--build-number=#{build_number}")
    end

    changelog_from_git_commits(
      pretty: "- %s",
      date_format: "short",
      match_lightweight_tag: false,
      commits_count: 5,
    )
    
    slack(
      message: "App successfully built!",
      payload: {
        "Download URL" => lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]
      }
    )
  end

  error do |lane, exception, options|
    slack(message: "Lane failed with exception : #{exception.message}", success: false)
    UI.build_failure!(exception)
  end

end
