name: Android CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: download Flutter
      run: wget --quiet --output-document=$HOME/flutter-sdk.zip https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.9.1+hotfix.2-stable.zip
    - name: install Flutter
      run: /usr/bin/unzip -q $HOME/flutter-sdk.zip -d $HOME 
    - name: set up Flutter tools 
      run: export PATH="$PATH:$HOME/flutter/bin" && flutter precache
    - name: Build Android APK
      run: export PATH="$PATH:$HOME/flutter/bin" && cd app/notes-app && echo $GOOGLE_SECRETS > android/app/google-services.json && flutter build apk --release && cd android/ && fastlane android beta
      env:
        SLACK_URL: ${{ secrets.SLACK_URL}}
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
        APPCENTER_OWNER_NAME: ${{ secrets.APPCENTER_OWNER_NAME }}
        GOOGLE_SECRETS: ${{ secrets.GOOGLE_SECRETS }}
