name: Android CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    timeout-minutes: 70

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: download Flutter
      run: wget --quiet --output-document=$HOME/flutter-sdk.zip https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.9.1+hotfix.2-stable.zip
    - name: install Flutter
      run: /usr/bin/unzip -q $HOME/flutter-sdk.zip -d $HOME 
    - name: set up Flutter tools 
      run: export PATH="$PATH:$HOME/flutter/bin" && flutter precache
    - name: set up secrets
      run: cd app/notes-app/android/ && echo -n $ANDROID_KEYPROPERTIES | base64 -D > key.properties && echo -n $ANDROID_KEYSTORE | base64 -D > app/android_release.jks && echo $GOOGLE_SECRETS > app/google-services.json
      env:
        GOOGLE_SECRETS: ${{ secrets.GOOGLE_SECRETS }}
        ANDROID_KEYPROPERTIES: ${{ secrets.ANDROID_KEYPROPERTIES }}
        ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
    - name: Build Android APK
      run: export PATH="$PATH:$HOME/flutter/bin" && cd app/notes-app/android/ && fastlane android beta
      env:
        SLACK_URL: ${{ secrets.SLACK_URL}}
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
        APPCENTER_OWNER_NAME: ${{ secrets.APPCENTER_OWNER_NAME }}
